// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Promuse.Persistence;

#nullable disable

namespace Promuse.Persistence.Migrations
{
    [DbContext(typeof(PromuseDbContext))]
    [Migration("20261010144619_GachaBannersAndPulls")]
    partial class GachaBannersAndPulls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Promuse.Persistence.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_id");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_device_id")
                        .HasFilter("device_id IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_username")
                        .HasFilter("username IS NOT NULL");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.GachaBanner", b =>
                {
                    b.Property<string>("BannerId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("banner_id");

                    b.Property<int>("CostMulti")
                        .HasColumnType("integer")
                        .HasColumnName("cost_multi");

                    b.Property<int>("CostSingle")
                        .HasColumnType("integer")
                        .HasColumnName("cost_single");

                    b.Property<int>("CurrencyItemId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_item_id");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("PityThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("pity_threshold");

                    b.Property<int>("RateFiveStar")
                        .HasColumnType("integer")
                        .HasColumnName("rate_five_star");

                    b.Property<int>("RateFourStar")
                        .HasColumnType("integer")
                        .HasColumnName("rate_four_star");

                    b.Property<int>("RateThreeStar")
                        .HasColumnType("integer")
                        .HasColumnName("rate_three_star");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<int?>("TicketItemId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_item_id");

                    b.HasKey("BannerId")
                        .HasName("pk_gacha_banners");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_gacha_banners_sort_order");

                    b.ToTable("gacha_banners", null, t =>
                        {
                            t.HasCheckConstraint("ck_gacha_banners_positive", "pity_threshold > 0 AND cost_single > 0 AND cost_multi > 0");

                            t.HasCheckConstraint("ck_gacha_banners_rates", "rate_five_star >= 0 AND rate_four_star >= 0 AND rate_three_star >= 0 AND rate_five_star + rate_four_star + rate_three_star = 10000");

                            t.HasCheckConstraint("ck_gacha_banners_window", "starts_at IS NULL OR ends_at IS NULL OR starts_at < ends_at");
                        });

                    b.HasData(
                        new
                        {
                            BannerId = "event_amiya",
                            CostMulti = 1800,
                            CostSingle = 180,
                            CurrencyItemId = 1,
                            EndsAt = new DateTimeOffset(new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            PityThreshold = 30,
                            RateFiveStar = 200,
                            RateFourStar = 1000,
                            RateThreeStar = 8800,
                            SortOrder = 1,
                            StartsAt = new DateTimeOffset(new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            TicketItemId = 10
                        },
                        new
                        {
                            BannerId = "standard",
                            CostMulti = 1800,
                            CostSingle = 180,
                            CurrencyItemId = 1,
                            IsActive = true,
                            PityThreshold = 30,
                            RateFiveStar = 200,
                            RateFourStar = 1000,
                            RateThreeStar = 8800,
                            SortOrder = 2,
                            TicketItemId = 10
                        });
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.GachaPity", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("BannerId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("banner_id");

                    b.Property<int>("PullsSinceFiveStar")
                        .HasColumnType("integer")
                        .HasColumnName("pulls_since_five_star");

                    b.HasKey("AccountId", "BannerId")
                        .HasName("pk_gacha_pity");

                    b.HasIndex("BannerId")
                        .HasDatabaseName("ix_gacha_pity_banner_id");

                    b.ToTable("gacha_pity", null, t =>
                        {
                            t.HasCheckConstraint("ck_gacha_pity_not_negative", "pulls_since_five_star >= 0");
                        });
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.GachaPoolEntry", b =>
                {
                    b.Property<string>("BannerId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("banner_id");

                    b.Property<string>("CharacterId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("character_id");

                    b.Property<int>("DuplicateAmount")
                        .HasColumnType("integer")
                        .HasColumnName("duplicate_amount");

                    b.Property<int>("DuplicateItemId")
                        .HasColumnType("integer")
                        .HasColumnName("duplicate_item_id");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasColumnName("rarity");

                    b.HasKey("BannerId", "CharacterId")
                        .HasName("pk_gacha_pool_entries");

                    b.ToTable("gacha_pool_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_gacha_pool_entries_values", "rarity BETWEEN 3 AND 5 AND duplicate_amount > 0");
                        });

                    b.HasData(
                        new
                        {
                            BannerId = "event_amiya",
                            CharacterId = "AMIYA",
                            DuplicateAmount = 20,
                            DuplicateItemId = 8,
                            Rarity = 5
                        },
                        new
                        {
                            BannerId = "event_amiya",
                            CharacterId = "NOVA",
                            DuplicateAmount = 5,
                            DuplicateItemId = 8,
                            Rarity = 4
                        },
                        new
                        {
                            BannerId = "event_amiya",
                            CharacterId = "ECHO",
                            DuplicateAmount = 5,
                            DuplicateItemId = 8,
                            Rarity = 4
                        },
                        new
                        {
                            BannerId = "event_amiya",
                            CharacterId = "PULSE",
                            DuplicateAmount = 1,
                            DuplicateItemId = 8,
                            Rarity = 3
                        },
                        new
                        {
                            BannerId = "standard",
                            CharacterId = "AMIYA",
                            DuplicateAmount = 20,
                            DuplicateItemId = 8,
                            Rarity = 5
                        },
                        new
                        {
                            BannerId = "standard",
                            CharacterId = "NOVA",
                            DuplicateAmount = 5,
                            DuplicateItemId = 8,
                            Rarity = 4
                        },
                        new
                        {
                            BannerId = "standard",
                            CharacterId = "ECHO",
                            DuplicateAmount = 5,
                            DuplicateItemId = 8,
                            Rarity = 4
                        },
                        new
                        {
                            BannerId = "standard",
                            CharacterId = "PULSE",
                            DuplicateAmount = 1,
                            DuplicateItemId = 8,
                            Rarity = 3
                        });
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.GachaPull", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("BannerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("banner_id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("character_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Guaranteed")
                        .HasColumnType("boolean")
                        .HasColumnName("guaranteed");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean")
                        .HasColumnName("is_new");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer")
                        .HasColumnName("rarity");

                    b.HasKey("Id")
                        .HasName("pk_gacha_pulls");

                    b.HasIndex("BannerId")
                        .HasDatabaseName("ix_gacha_pulls_banner_id");

                    b.HasIndex("AccountId", "Id")
                        .HasDatabaseName("ix_gacha_pulls_account_id_id");

                    b.ToTable("gacha_pulls", (string)null);
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("endpoint");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_records_expires_at");

                    b.HasIndex("Key", "Endpoint")
                        .IsUnique()
                        .HasDatabaseName("ix_idempotency_records_key_endpoint");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.LeaderboardScore", b =>
                {
                    b.Property<string>("StageId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stage_id");

                    b.Property<string>("PeriodKey")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("period_key");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("AchievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("achieved_at");

                    b.Property<string>("CharacterId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("character_id");

                    b.Property<int>("MaxCombo")
                        .HasColumnType("integer")
                        .HasColumnName("max_combo");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("StageId", "PeriodKey", "AccountId")
                        .HasName("pk_leaderboard_scores");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_leaderboard_scores_account_id");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_leaderboard_scores_run_id");

                    b.HasIndex("StageId", "PeriodKey", "Score", "AchievedAt")
                        .IsDescending(false, false, true, false)
                        .HasDatabaseName("ix_leaderboard_scores_stage_id_period_key_score_achieved_at");

                    b.ToTable("leaderboard_scores", (string)null);
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.MissionClaim", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Tab")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tab");

                    b.Property<string>("MissionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("mission_id");

                    b.Property<string>("PeriodKey")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("period_key");

                    b.Property<DateTimeOffset>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.HasKey("AccountId", "Tab", "MissionId", "PeriodKey")
                        .HasName("pk_mission_claims");

                    b.ToTable("mission_claims", (string)null);
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.MissionCounter", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Tab")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tab");

                    b.Property<string>("Goal")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("goal");

                    b.Property<string>("PeriodKey")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("period_key");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.HasKey("AccountId", "Tab", "Goal", "PeriodKey")
                        .HasName("pk_mission_counters");

                    b.ToTable("mission_counters", (string)null);
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.MissionDefinition", b =>
                {
                    b.Property<string>("Tab")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tab");

                    b.Property<string>("MissionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("mission_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("goal");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("Target")
                        .HasColumnType("integer")
                        .HasColumnName("target");

                    b.HasKey("Tab", "MissionId")
                        .HasName("pk_mission_definitions");

                    b.ToTable("mission_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_mission_definitions_target_positive", "target > 0 AND points > 0");
                        });

                    b.HasData(
                        new
                        {
                            Tab = "Daily",
                            MissionId = "daily.play1",
                            Description = "Clear any song 1 time(s)",
                            Goal = "PlaySong",
                            IsActive = true,
                            Points = 1,
                            SortOrder = 1,
                            Target = 1
                        },
                        new
                        {
                            Tab = "Daily",
                            MissionId = "daily.play2",
                            Description = "Clear any song 2 time(s)",
                            Goal = "PlaySong",
                            IsActive = true,
                            Points = 2,
                            SortOrder = 2,
                            Target = 2
                        },
                        new
                        {
                            Tab = "Daily",
                            MissionId = "daily.buy1",
                            Description = "Purchase any item from the Store 1 time(s)",
                            Goal = "BuyShopItem",
                            IsActive = true,
                            Points = 3,
                            SortOrder = 3,
                            Target = 1
                        },
                        new
                        {
                            Tab = "Weekly",
                            MissionId = "weekly.play5",
                            Description = "Clear any song 5 time(s)",
                            Goal = "PlaySong",
                            IsActive = true,
                            Points = 2,
                            SortOrder = 1,
                            Target = 5
                        },
                        new
                        {
                            Tab = "Weekly",
                            MissionId = "weekly.play10",
                            Description = "Clear any song 10 time(s)",
                            Goal = "PlaySong",
                            IsActive = true,
                            Points = 3,
                            SortOrder = 2,
                            Target = 10
                        },
                        new
                        {
                            Tab = "Weekly",
                            MissionId = "weekly.buy3",
                            Description = "Purchase any item from the Store 3 time(s)",
                            Goal = "BuyShopItem",
                            IsActive = true,
                            Points = 5,
                            SortOrder = 3,
                            Target = 3
                        });
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.MissionRewardClaim", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Tab")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tab");

                    b.Property<string>("RewardId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reward_id");

                    b.Property<string>("PeriodKey")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("period_key");

                    b.Property<DateTimeOffset>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.HasKey("AccountId", "Tab", "RewardId", "PeriodKey")
                        .HasName("pk_mission_reward_claims");

                    b.ToTable("mission_reward_claims", (string)null);
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.MissionRewardDefinition", b =>
                {
                    b.Property<string>("Tab")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tab");

                    b.Property<string>("RewardId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reward_id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("RequiredPoints")
                        .HasColumnType("integer")
                        .HasColumnName("required_points");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Tab", "RewardId")
                        .HasName("pk_mission_reward_definitions");

                    b.ToTable("mission_reward_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_mission_rewards_positive", "required_points > 0 AND amount > 0");
                        });

                    b.HasData(
                        new
                        {
                            Tab = "Daily",
                            RewardId = "daily.r1",
                            Amount = 500,
                            IsActive = true,
                            ItemId = 2,
                            RequiredPoints = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            Tab = "Daily",
                            RewardId = "daily.r2",
                            Amount = 100,
                            IsActive = true,
                            ItemId = 1,
                            RequiredPoints = 2,
                            SortOrder = 2
                        },
                        new
                        {
                            Tab = "Daily",
                            RewardId = "daily.r3",
                            Amount = 3,
                            IsActive = true,
                            ItemId = 6,
                            RequiredPoints = 3,
                            SortOrder = 3
                        },
                        new
                        {
                            Tab = "Weekly",
                            RewardId = "weekly.r1",
                            Amount = 2000,
                            IsActive = true,
                            ItemId = 2,
                            RequiredPoints = 3,
                            SortOrder = 1
                        },
                        new
                        {
                            Tab = "Weekly",
                            RewardId = "weekly.r2",
                            Amount = 300,
                            IsActive = true,
                            ItemId = 1,
                            RequiredPoints = 6,
                            SortOrder = 2
                        },
                        new
                        {
                            Tab = "Weekly",
                            RewardId = "weekly.r3",
                            Amount = 5,
                            IsActive = true,
                            ItemId = 7,
                            RequiredPoints = 10,
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.Player", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DesktopCharacterId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("desktop_character_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("display_name");

                    b.Property<int>("Exp")
                        .HasColumnType("integer")
                        .HasColumnName("exp");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer")
                        .HasColumnName("stamina");

                    b.Property<DateTimeOffset>("StaminaUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stamina_updated_at");

                    b.Property<int>("StateVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("state_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AccountId")
                        .HasName("pk_players");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.PlayerCharacter", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("CharacterId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("character_id");

                    b.Property<int>("Elite")
                        .HasColumnType("integer")
                        .HasColumnName("elite");

                    b.Property<int>("Exp")
                        .HasColumnType("integer")
                        .HasColumnName("exp");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("Trust")
                        .HasColumnType("integer")
                        .HasColumnName("trust");

                    b.HasKey("AccountId", "CharacterId")
                        .HasName("pk_player_characters");

                    b.ToTable("player_characters", (string)null);
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.PlayerItem", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.HasKey("AccountId", "ItemId")
                        .HasName("pk_player_items");

                    b.ToTable("player_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_player_items_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("PriceAmountTotal")
                        .HasColumnType("integer")
                        .HasColumnName("price_amount_total");

                    b.Property<int>("PriceItemId")
                        .HasColumnType("integer")
                        .HasColumnName("price_item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("SellAmountTotal")
                        .HasColumnType("integer")
                        .HasColumnName("sell_amount_total");

                    b.Property<int>("SellItemId")
                        .HasColumnType("integer")
                        .HasColumnName("sell_item_id");

                    b.Property<Guid>("ShopOfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_offer_id");

                    b.HasKey("Id")
                        .HasName("pk_purchases");

                    b.HasIndex("ShopOfferId")
                        .HasDatabaseName("ix_purchases_shop_offer_id");

                    b.HasIndex("AccountId", "CreatedAt")
                        .HasDatabaseName("ix_purchases_account_id_created_at");

                    b.ToTable("purchases", null, t =>
                        {
                            t.HasCheckConstraint("ck_purchases_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_refresh_tokens_account_id");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("CharacterId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("character_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<long>("Seed")
                        .HasColumnType("bigint")
                        .HasColumnName("seed");

                    b.Property<string>("StageId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stage_id");

                    b.Property<int>("StaminaSpent")
                        .HasColumnType("integer")
                        .HasColumnName("stamina_spent");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<bool?>("Won")
                        .HasColumnType("boolean")
                        .HasColumnName("won");

                    b.HasKey("Id")
                        .HasName("pk_runs");

                    b.HasIndex("AccountId", "StartedAt")
                        .HasDatabaseName("ix_runs_account_id_started_at");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.RunScore", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int?>("Ceiling")
                        .HasColumnType("integer")
                        .HasColumnName("ceiling");

                    b.Property<bool>("ClaimedWon")
                        .HasColumnType("boolean")
                        .HasColumnName("claimed_won");

                    b.PrimitiveCollection<string[]>("Flags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("flags");

                    b.Property<double?>("FrameIntervalMs")
                        .HasColumnType("double precision")
                        .HasColumnName("frame_interval_ms");

                    b.Property<bool>("FullCombo")
                        .HasColumnType("boolean")
                        .HasColumnName("full_combo");

                    b.Property<int>("Great")
                        .HasColumnType("integer")
                        .HasColumnName("great");

                    b.Property<int>("Hit")
                        .HasColumnType("integer")
                        .HasColumnName("hit");

                    b.Property<int>("MaxCombo")
                        .HasColumnType("integer")
                        .HasColumnName("max_combo");

                    b.Property<int>("Miss")
                        .HasColumnType("integer")
                        .HasColumnName("miss");

                    b.Property<int>("Perfect")
                        .HasColumnType("integer")
                        .HasColumnName("perfect");

                    b.Property<int>("Presses")
                        .HasColumnType("integer")
                        .HasColumnName("presses");

                    b.PrimitiveCollection<string[]>("Reasons")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("reasons");

                    b.Property<string>("RulesetFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ruleset_fingerprint");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("StageId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stage_id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<double?>("TimingMeanMs")
                        .HasColumnType("double precision")
                        .HasColumnName("timing_mean_ms");

                    b.Property<int?>("TimingSamples")
                        .HasColumnType("integer")
                        .HasColumnName("timing_samples");

                    b.Property<double?>("TimingStdDevMs")
                        .HasColumnType("double precision")
                        .HasColumnName("timing_std_dev_ms");

                    b.Property<byte[]>("Trace")
                        .HasColumnType("bytea")
                        .HasColumnName("trace");

                    b.Property<int>("TraceFrames")
                        .HasColumnType("integer")
                        .HasColumnName("trace_frames");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("verdict");

                    b.HasKey("RunId")
                        .HasName("pk_run_scores");

                    b.HasIndex("Verdict")
                        .HasDatabaseName("ix_run_scores_verdict");

                    b.HasIndex("AccountId", "SubmittedAt")
                        .HasDatabaseName("ix_run_scores_account_id_submitted_at");

                    b.ToTable("run_scores", null, t =>
                        {
                            t.HasCheckConstraint("ck_run_scores_not_negative", "score >= 0 AND max_combo >= 0 AND perfect >= 0 AND great >= 0 AND hit >= 0 AND miss >= 0");
                        });
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.ShopOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("PriceAmount")
                        .HasColumnType("integer")
                        .HasColumnName("price_amount");

                    b.Property<int>("PriceItemId")
                        .HasColumnType("integer")
                        .HasColumnName("price_item_id");

                    b.Property<int>("SellAmount")
                        .HasColumnType("integer")
                        .HasColumnName("sell_amount");

                    b.Property<int>("SellItemId")
                        .HasColumnType("integer")
                        .HasColumnName("sell_item_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_shop_offers");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_shop_offers_sort_order");

                    b.ToTable("shop_offers", null, t =>
                        {
                            t.HasCheckConstraint("ck_shop_offers_amounts_positive", "sell_amount > 0 AND price_amount > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            IsActive = true,
                            PriceAmount = 240,
                            PriceItemId = 6,
                            SellAmount = 1,
                            SellItemId = 10,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            IsActive = true,
                            PriceAmount = 10,
                            PriceItemId = 6,
                            SellAmount = 4000,
                            SellItemId = 2,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            IsActive = true,
                            PriceAmount = 10,
                            PriceItemId = 6,
                            SellAmount = 1,
                            SellItemId = 11,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            IsActive = true,
                            PriceAmount = 40,
                            PriceItemId = 6,
                            SellAmount = 100,
                            SellItemId = 1,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            IsActive = true,
                            PriceAmount = 8,
                            PriceItemId = 6,
                            SellAmount = 1,
                            SellItemId = 12,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000006"),
                            IsActive = true,
                            PriceAmount = 12,
                            PriceItemId = 6,
                            SellAmount = 1,
                            SellItemId = 13,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000007"),
                            IsActive = true,
                            PriceAmount = 40,
                            PriceItemId = 8,
                            SellAmount = 1,
                            SellItemId = 10,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000008"),
                            IsActive = true,
                            PriceAmount = 5,
                            PriceItemId = 8,
                            SellAmount = 2000,
                            SellItemId = 2,
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.SquadSlot", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("Slot")
                        .HasColumnType("integer")
                        .HasColumnName("slot");

                    b.Property<string>("CharacterId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("character_id");

                    b.HasKey("AccountId", "Slot")
                        .HasName("pk_squad_slots");

                    b.ToTable("squad_slots", null, t =>
                        {
                            t.HasCheckConstraint("ck_squad_slots_range", "slot >= 0 AND slot <= 3");
                        });
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.Stage", b =>
                {
                    b.Property<string>("StageId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stage_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("StaminaCost")
                        .HasColumnType("integer")
                        .HasColumnName("stamina_cost");

                    b.HasKey("StageId")
                        .HasName("pk_stages");

                    b.ToTable("stages", null, t =>
                        {
                            t.HasCheckConstraint("ck_stages_cost_not_negative", "stamina_cost >= 0");
                        });

                    b.HasData(
                        new
                        {
                            StageId = "stage_001",
                            IsActive = true,
                            StaminaCost = 6
                        },
                        new
                        {
                            StageId = "stage_AIW",
                            IsActive = true,
                            StaminaCost = 6
                        },
                        new
                        {
                            StageId = "stage_AIW_hard",
                            IsActive = true,
                            StaminaCost = 12
                        });
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.GachaPity", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gacha_pity_players_account_id");

                    b.HasOne("Promuse.Persistence.Entities.GachaBanner", null)
                        .WithMany()
                        .HasForeignKey("BannerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gacha_pity_gacha_banners_banner_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.GachaPoolEntry", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.GachaBanner", "Banner")
                        .WithMany("Pool")
                        .HasForeignKey("BannerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gacha_pool_entries_gacha_banners_banner_id");

                    b.Navigation("Banner");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.GachaPull", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gacha_pulls_players_account_id");

                    b.HasOne("Promuse.Persistence.Entities.GachaBanner", null)
                        .WithMany()
                        .HasForeignKey("BannerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_gacha_pulls_gacha_banners_banner_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.LeaderboardScore", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leaderboard_scores_players_account_id");

                    b.HasOne("Promuse.Persistence.Entities.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leaderboard_scores_runs_run_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.MissionClaim", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mission_claims_players_account_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.MissionCounter", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mission_counters_players_account_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.MissionRewardClaim", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mission_reward_claims_players_account_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.Player", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Account", "Account")
                        .WithOne("Player")
                        .HasForeignKey("Promuse.Persistence.Entities.Player", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_players_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.PlayerCharacter", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Player", "Player")
                        .WithMany("Characters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_characters_players_account_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.PlayerItem", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Player", "Player")
                        .WithMany("Items")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_items_players_account_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.Purchase", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchases_players_account_id");

                    b.HasOne("Promuse.Persistence.Entities.ShopOffer", "Offer")
                        .WithMany()
                        .HasForeignKey("ShopOfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchases_shop_offers_shop_offer_id");

                    b.Navigation("Offer");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.RefreshToken", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.Run", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_runs_players_account_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.RunScore", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Run", "Run")
                        .WithOne()
                        .HasForeignKey("Promuse.Persistence.Entities.RunScore", "RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_scores_runs_run_id");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.SquadSlot", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Player", "Player")
                        .WithMany("Squad")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_squad_slots_players_account_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.Account", b =>
                {
                    b.Navigation("Player");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.GachaBanner", b =>
                {
                    b.Navigation("Pool");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.Player", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Items");

                    b.Navigation("Squad");
                });
#pragma warning restore 612, 618
        }
    }
}
