// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Promuse.Persistence;

#nullable disable

namespace Promuse.Persistence.Migrations
{
    [DbContext(typeof(PromuseDbContext))]
    [Migration("20260928025349_MissionBoards")]
    partial class MissionBoards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Promuse.Persistence.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_id");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_device_id")
                        .HasFilter("device_id IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_username")
                        .HasFilter("username IS NOT NULL");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("endpoint");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_records");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_records_expires_at");

                    b.HasIndex("Key", "Endpoint")
                        .IsUnique()
                        .HasDatabaseName("ix_idempotency_records_key_endpoint");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.MissionClaim", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Tab")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tab");

                    b.Property<string>("MissionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("mission_id");

                    b.Property<string>("PeriodKey")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("period_key");

                    b.Property<DateTimeOffset>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.HasKey("AccountId", "Tab", "MissionId", "PeriodKey")
                        .HasName("pk_mission_claims");

                    b.ToTable("mission_claims", (string)null);
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.MissionCounter", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Tab")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tab");

                    b.Property<string>("Goal")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("goal");

                    b.Property<string>("PeriodKey")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("period_key");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.HasKey("AccountId", "Tab", "Goal", "PeriodKey")
                        .HasName("pk_mission_counters");

                    b.ToTable("mission_counters", (string)null);
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.MissionDefinition", b =>
                {
                    b.Property<string>("Tab")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tab");

                    b.Property<string>("MissionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("mission_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("goal");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("Target")
                        .HasColumnType("integer")
                        .HasColumnName("target");

                    b.HasKey("Tab", "MissionId")
                        .HasName("pk_mission_definitions");

                    b.ToTable("mission_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_mission_definitions_target_positive", "target > 0 AND points > 0");
                        });

                    b.HasData(
                        new
                        {
                            Tab = "Daily",
                            MissionId = "daily.play1",
                            Description = "Clear any song 1 time(s)",
                            Goal = "PlaySong",
                            IsActive = true,
                            Points = 1,
                            SortOrder = 1,
                            Target = 1
                        },
                        new
                        {
                            Tab = "Daily",
                            MissionId = "daily.play2",
                            Description = "Clear any song 2 time(s)",
                            Goal = "PlaySong",
                            IsActive = true,
                            Points = 2,
                            SortOrder = 2,
                            Target = 2
                        },
                        new
                        {
                            Tab = "Daily",
                            MissionId = "daily.buy1",
                            Description = "Purchase any item from the Store 1 time(s)",
                            Goal = "BuyShopItem",
                            IsActive = true,
                            Points = 3,
                            SortOrder = 3,
                            Target = 1
                        },
                        new
                        {
                            Tab = "Weekly",
                            MissionId = "weekly.play5",
                            Description = "Clear any song 5 time(s)",
                            Goal = "PlaySong",
                            IsActive = true,
                            Points = 2,
                            SortOrder = 1,
                            Target = 5
                        },
                        new
                        {
                            Tab = "Weekly",
                            MissionId = "weekly.play10",
                            Description = "Clear any song 10 time(s)",
                            Goal = "PlaySong",
                            IsActive = true,
                            Points = 3,
                            SortOrder = 2,
                            Target = 10
                        },
                        new
                        {
                            Tab = "Weekly",
                            MissionId = "weekly.buy3",
                            Description = "Purchase any item from the Store 3 time(s)",
                            Goal = "BuyShopItem",
                            IsActive = true,
                            Points = 5,
                            SortOrder = 3,
                            Target = 3
                        });
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.MissionRewardClaim", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Tab")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tab");

                    b.Property<string>("RewardId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reward_id");

                    b.Property<string>("PeriodKey")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("period_key");

                    b.Property<DateTimeOffset>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.HasKey("AccountId", "Tab", "RewardId", "PeriodKey")
                        .HasName("pk_mission_reward_claims");

                    b.ToTable("mission_reward_claims", (string)null);
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.MissionRewardDefinition", b =>
                {
                    b.Property<string>("Tab")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tab");

                    b.Property<string>("RewardId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reward_id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("RequiredPoints")
                        .HasColumnType("integer")
                        .HasColumnName("required_points");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Tab", "RewardId")
                        .HasName("pk_mission_reward_definitions");

                    b.ToTable("mission_reward_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_mission_rewards_positive", "required_points > 0 AND amount > 0");
                        });

                    b.HasData(
                        new
                        {
                            Tab = "Daily",
                            RewardId = "daily.r1",
                            Amount = 500,
                            IsActive = true,
                            ItemId = 2,
                            RequiredPoints = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            Tab = "Daily",
                            RewardId = "daily.r2",
                            Amount = 100,
                            IsActive = true,
                            ItemId = 1,
                            RequiredPoints = 2,
                            SortOrder = 2
                        },
                        new
                        {
                            Tab = "Daily",
                            RewardId = "daily.r3",
                            Amount = 3,
                            IsActive = true,
                            ItemId = 6,
                            RequiredPoints = 3,
                            SortOrder = 3
                        },
                        new
                        {
                            Tab = "Weekly",
                            RewardId = "weekly.r1",
                            Amount = 2000,
                            IsActive = true,
                            ItemId = 2,
                            RequiredPoints = 3,
                            SortOrder = 1
                        },
                        new
                        {
                            Tab = "Weekly",
                            RewardId = "weekly.r2",
                            Amount = 300,
                            IsActive = true,
                            ItemId = 1,
                            RequiredPoints = 6,
                            SortOrder = 2
                        },
                        new
                        {
                            Tab = "Weekly",
                            RewardId = "weekly.r3",
                            Amount = 5,
                            IsActive = true,
                            ItemId = 7,
                            RequiredPoints = 10,
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.Player", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DesktopCharacterId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("desktop_character_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("display_name");

                    b.Property<int>("Exp")
                        .HasColumnType("integer")
                        .HasColumnName("exp");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer")
                        .HasColumnName("stamina");

                    b.Property<DateTimeOffset>("StaminaUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stamina_updated_at");

                    b.Property<int>("StateVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("state_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AccountId")
                        .HasName("pk_players");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.PlayerCharacter", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("CharacterId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("character_id");

                    b.Property<int>("Elite")
                        .HasColumnType("integer")
                        .HasColumnName("elite");

                    b.Property<int>("Exp")
                        .HasColumnType("integer")
                        .HasColumnName("exp");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("Trust")
                        .HasColumnType("integer")
                        .HasColumnName("trust");

                    b.HasKey("AccountId", "CharacterId")
                        .HasName("pk_player_characters");

                    b.ToTable("player_characters", (string)null);
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.PlayerItem", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.HasKey("AccountId", "ItemId")
                        .HasName("pk_player_items");

                    b.ToTable("player_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_player_items_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("PriceAmountTotal")
                        .HasColumnType("integer")
                        .HasColumnName("price_amount_total");

                    b.Property<int>("PriceItemId")
                        .HasColumnType("integer")
                        .HasColumnName("price_item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("SellAmountTotal")
                        .HasColumnType("integer")
                        .HasColumnName("sell_amount_total");

                    b.Property<int>("SellItemId")
                        .HasColumnType("integer")
                        .HasColumnName("sell_item_id");

                    b.Property<Guid>("ShopOfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_offer_id");

                    b.HasKey("Id")
                        .HasName("pk_purchases");

                    b.HasIndex("ShopOfferId")
                        .HasDatabaseName("ix_purchases_shop_offer_id");

                    b.HasIndex("AccountId", "CreatedAt")
                        .HasDatabaseName("ix_purchases_account_id_created_at");

                    b.ToTable("purchases", null, t =>
                        {
                            t.HasCheckConstraint("ck_purchases_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_refresh_tokens_account_id");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<long>("Seed")
                        .HasColumnType("bigint")
                        .HasColumnName("seed");

                    b.Property<string>("StageId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stage_id");

                    b.Property<int>("StaminaSpent")
                        .HasColumnType("integer")
                        .HasColumnName("stamina_spent");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<bool?>("Won")
                        .HasColumnType("boolean")
                        .HasColumnName("won");

                    b.HasKey("Id")
                        .HasName("pk_runs");

                    b.HasIndex("AccountId", "StartedAt")
                        .HasDatabaseName("ix_runs_account_id_started_at");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.ShopOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("PriceAmount")
                        .HasColumnType("integer")
                        .HasColumnName("price_amount");

                    b.Property<int>("PriceItemId")
                        .HasColumnType("integer")
                        .HasColumnName("price_item_id");

                    b.Property<int>("SellAmount")
                        .HasColumnType("integer")
                        .HasColumnName("sell_amount");

                    b.Property<int>("SellItemId")
                        .HasColumnType("integer")
                        .HasColumnName("sell_item_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_shop_offers");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_shop_offers_sort_order");

                    b.ToTable("shop_offers", null, t =>
                        {
                            t.HasCheckConstraint("ck_shop_offers_amounts_positive", "sell_amount > 0 AND price_amount > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            IsActive = true,
                            PriceAmount = 240,
                            PriceItemId = 6,
                            SellAmount = 1,
                            SellItemId = 10,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            IsActive = true,
                            PriceAmount = 10,
                            PriceItemId = 6,
                            SellAmount = 4000,
                            SellItemId = 2,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            IsActive = true,
                            PriceAmount = 10,
                            PriceItemId = 6,
                            SellAmount = 1,
                            SellItemId = 11,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000004"),
                            IsActive = true,
                            PriceAmount = 40,
                            PriceItemId = 6,
                            SellAmount = 100,
                            SellItemId = 1,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            IsActive = true,
                            PriceAmount = 8,
                            PriceItemId = 6,
                            SellAmount = 1,
                            SellItemId = 12,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000006"),
                            IsActive = true,
                            PriceAmount = 12,
                            PriceItemId = 6,
                            SellAmount = 1,
                            SellItemId = 13,
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.SquadSlot", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<int>("Slot")
                        .HasColumnType("integer")
                        .HasColumnName("slot");

                    b.Property<string>("CharacterId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("character_id");

                    b.HasKey("AccountId", "Slot")
                        .HasName("pk_squad_slots");

                    b.ToTable("squad_slots", null, t =>
                        {
                            t.HasCheckConstraint("ck_squad_slots_range", "slot >= 0 AND slot <= 3");
                        });
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.Stage", b =>
                {
                    b.Property<string>("StageId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stage_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("StaminaCost")
                        .HasColumnType("integer")
                        .HasColumnName("stamina_cost");

                    b.HasKey("StageId")
                        .HasName("pk_stages");

                    b.ToTable("stages", null, t =>
                        {
                            t.HasCheckConstraint("ck_stages_cost_not_negative", "stamina_cost >= 0");
                        });

                    b.HasData(
                        new
                        {
                            StageId = "stage_001",
                            IsActive = true,
                            StaminaCost = 6
                        },
                        new
                        {
                            StageId = "stage_AIW",
                            IsActive = true,
                            StaminaCost = 6
                        },
                        new
                        {
                            StageId = "stage_AIW_hard",
                            IsActive = true,
                            StaminaCost = 12
                        });
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.MissionClaim", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mission_claims_players_account_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.MissionCounter", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mission_counters_players_account_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.MissionRewardClaim", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mission_reward_claims_players_account_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.Player", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Account", "Account")
                        .WithOne("Player")
                        .HasForeignKey("Promuse.Persistence.Entities.Player", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_players_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.PlayerCharacter", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Player", "Player")
                        .WithMany("Characters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_characters_players_account_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.PlayerItem", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Player", "Player")
                        .WithMany("Items")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_items_players_account_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.Purchase", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchases_players_account_id");

                    b.HasOne("Promuse.Persistence.Entities.ShopOffer", "Offer")
                        .WithMany()
                        .HasForeignKey("ShopOfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchases_shop_offers_shop_offer_id");

                    b.Navigation("Offer");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.RefreshToken", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.Run", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_runs_players_account_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.SquadSlot", b =>
                {
                    b.HasOne("Promuse.Persistence.Entities.Player", "Player")
                        .WithMany("Squad")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_squad_slots_players_account_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.Account", b =>
                {
                    b.Navigation("Player");
                });

            modelBuilder.Entity("Promuse.Persistence.Entities.Player", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Items");

                    b.Navigation("Squad");
                });
#pragma warning restore 612, 618
        }
    }
}
